### ISSUE TITLE
DecompressScanlines::read_scanlines is unsound

### ISSUE THREAD

**Issue by HeroicKatora** [ImageOptim/mozjpeg-rust#10]
> https://docs.rs/mozjpeg/0.8.17/mozjpeg/decompress/struct.DecompressStarted.html#method.read_scanlines

This method will write arbitrary, user controlled bytes into a slice of `T: Copy`. This can lead to invalid instances of `T` to be returned. Same reason as [`rgb`](https://github.com/kornelski/rust-rgb/issues/35) but without the `'static` bound so a little different. This can be used to decode scanlines into a `Vec<&'static u8>` or something along those lines and dereference some arbitrary memory with a crafted input file. No writable variant this time.

**Comment by kornelski** [comment]
Thanks. It's going to be `plain` crate again. I'm waiting for https://github.com/randomites/plain/pull/5 because I've noticed that crate has a big omission in impls.

**Comment by kornelski** [comment]
Fixed in 0.8.19
