### ISSUE TITLE
Add some encoding examples

### ISSUE THREAD

**Issue by tylerhawkes** [ImageOptim/mozjpeg-rust#12]
As someone who isn't familiar with libjpeg, it would be nice to have some encoding examples as well as some better documentation on the related functions.

**Comment by kornelski** [comment]
I intended to design a nicer interface for encoding, but haven't finished that.

**Comment by tylerhawkes** [comment]
Turns out the tests will probably give me what I need, but it would be nice to have examples at some point.

**Comment by kornelski** [comment]
https://docs.rs/mozjpeg/latest/mozjpeg/#encoding-example
