### ISSUE TITLE
Add mozjpeg-rust as encoder to image crate

### ISSUE THREAD

**Issue by godofdream** [ImageOptim/mozjpeg-rust#14]
As https://github.com/image-rs/image is getting more mature it would make sense to add mozjpeg as an full featured jpegencoder.
What do you think?

**Comment by kornelski** [comment]
image-rs is pure Rust. This crate is based on libjpeg-turbo, which is mostly C.

In the long term it would be cool to take SIMD-accelerated routines from libjpeg-turbo and replace C glue code with Rust, but that's a lot of work.
