### ISSUE TITLE
mozjpeg can unwind through `extern "C" fn` boundary, which is UB

### ISSUE THREAD

**Issue by SludgePhD** [ImageOptim/mozjpeg-rust#35]
This `extern "C" fn` explicitly unwinds:

https://github.com/ImageOptim/mozjpeg-rust/blob/d0acb82928625e4828ca48b3a6c703c36178a971/src/errormgr.rs#L37-L41

Additionally, it seemingly intentionally makes my program silently exit with an error status, without printing the actual error to stderr. Why? :laughing:

**Comment by kornelski** [comment]
Yes, I'm waiting for `extern "C-unwind"` to be stabilized. Until then it's technically UB.

**Comment by kornelski** [comment]
C-unwind is now stable.
