### ISSUE TITLE
could not build staticlib

### ISSUE THREAD

**Issue by nguyencse** [ImageOptim/mozjpeg-rust#37]
I could not build `staticlib` for ios target using command `cargo lipo --release`.
It told me that `failed to run custom build command for mozjpeg-sys v2.0.3`.
I really appreciate for your help.

**Comment by kornelski** [comment]
Before the text "failed to run custom build command for mozjpeg-sys v2.0.3" there should be explanation why it failed.

**Comment by nguyencse** [comment]
@kornelski thank you for your quick response.
before that text, it told me that `vendor/simd/arm/aarch64/jsimd.c:33:8: error: thread-local storage is not supported for the current target`

how can I pass this issue?

**Comment by kornelski** [comment]
You must set deployment target for iOS higher than ios9. 

    export IPHONEOS_DEPLOYMENT_TARGET=13.0

**Comment by kornelski** [comment]
You run:

```bash
export IPHONEOS_DEPLOYMENT_TARGET=13.0
cargo lipo --release
```

or use [cargo-xcode](https://lib.rs/crates/cargo-xcode) and set the target in Xcode.

**Comment by nguyencse** [comment]
Thank you for your sample command.
I found out that what we need is adding a variable to section [env] in config.toml file and run `cago lipo --release` again.
`[env]
IPHONEOS_DEPLOYMENT_TARGET = "13.0"`
