### ISSUE TITLE
Undefined behaviour in Compress::start_compress and CompressStarted::finish

### ISSUE THREAD

**Issue by jasonyu1996** [ImageOptim/mozjpeg-rust#43]
Hi! In `compress.rs`, `Compress::start_compress` creates a `DestinationMgr` in `started.dest_mgr` and places a pointer to it in `cinfo.dest`:
https://github.com/ImageOptim/mozjpeg-rust/blob/10dc5477ee5d71f78d8f9af486ef0a081fc18ae1/src/compress.rs#L118-L126

Then `CompressStarted::finish` mutates the content of this `DestinationMgr` through `cinfo.dest`:
https://github.com/ImageOptim/mozjpeg-rust/blob/10dc5477ee5d71f78d8f9af486ef0a081fc18ae1/src/compress.rs#L458-L460

This is an undefined behaviour and therefore has a risk of miscompilation. 
A simplified demo (https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=d22f202c6423ead0fda7cb649e47f536) shows different results under release and debug modes. MIRI reports this issue in this simplified demo.

**Comment by kornelski** [comment]
Thanks for the report. That was a tricky case!
