### ISSUE TITLE
Jpegli

### ISSUE THREAD

**Issue by si14** [ImageOptim/mozjpeg-rust#44]
First of all, thank you for mozjpeg-rust!

Do you plan to swap/enable [Jpegli](https://opensource.googleblog.com/2024/04/introducing-jpegli-new-jpeg-coding-library.html)? It seems to be an almost drop-in replacement and also just all around better. It's a bit of a selfish query, since there's [a fork swapping mozjpeg for Jpegli](https://github.com/Szpadel/jpegli-rs), but it doesn't keep up with the upstream, and it'd be lovely to have an upstream option to use Jpegli.

**Comment by kornelski** [comment]
Jpegli seems cool, but I haven't had time to investigate it closely yet. 

Anyway, this crate is for MozJPEG, so I'm not planning to replace the codec here.

**Comment by si14** [comment]
Fair enough! Hope you take a look at it some time, I'd trust your implementation way more than my own. I'll close the issue then since it's not really an issue.
